version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Pre-build phase started on `date`"
      - java -version
  build:
    commands:
      - echo "Build phase started on `date`"
      - chmod +x ./gradlew
      - ./gradlew clean build -x test
  post_build:
    commands:
      - echo "Build completed on `date`"
      - ./gradlew test jacocoTestReport

artifacts:
  files:
    - module-pay/build/libs/*.jar
    - module-common/build/libs/*.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'
