spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    root: WARN
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
  file:
    name: ./logs/application-test.log