spring:
  application:
    name: pay
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    master:
      jdbc-url: jdbc:h2:mem:testdb;
      username: sa
      password:
      driver-class-name: org.h2.Driver
    slave:
      jdbc-url: jdbc:h2:mem:testdb;
      username: sa
      password:
      driver-class-name: org.h2.Driver
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  redis:
    host: localhost
    port: 6379
  jwt:
    secret: ZGF5b25lLXNwcmluZy1ib290LWRpdmlkZW5kLXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldC1rZXkK

payment:
  toss:
    test_secrete_api_key: test_sk_5OWRapdA8djRMAk1nBbWVo1zEqZK
    success_url: http://localhost:8080/api/v1/payments/toss/success
    fail_url: http://localhost:8080/api/v1/payments/toss/fail

restricted:
  urls:
    - /restricted
    - /secret
    - /admin

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    com.example.pay: DEBUG
    org.springframework.boot.autoconfigure: WARN
  file:
    name: ./logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

debug: false

spring.autoconfigure.exclude:
  - org.springframework.boot.autoconfigure.context.ConfigurationPropertiesAutoConfiguration

---
spring:
  config:
    activate:
      on-profile: dev


---
spring:
  config:
    activate:
      on-profile: test


---
spring:
  config:
    activate:
      on-profile: prod

